name: Justin Schauble
favicon: null
layout_spectrum: 0.6262849601916969
typography_spectrum: 0.17830616142600775
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.125
  lightness: 0.2981492674443871
  saturation: 0.6875
  rhythmicContrast: 0.6738047662656754
purpose: []
